In [1]:
import pandas as pd

df6 = pd.DataFrame({
    "name": ["Ravi", "Amit"],
    "skills": [["Python", "SQL"], ["Java", "C++"]]
})

df6.explode("skills")

   name  skills
0  Ravi  Python
0  Ravi     SQL
1  Amit    Java
1  Amit     C++

In [2]:
df7 = pd.DataFrame({
    "name": ["Ravi"],
    "skills": [["Python", "SQL"]],
    "level": [["Advanced", "Beginner"]]
})

df7.explode(["skills", "level"])

   name  skills     level
0  Ravi  Python  Advanced
0  Ravi     SQL  Beginner

In [3]:
df8 = pd.DataFrame({
    "name": ["Ravi", "Amit"],
    "skills": [["Python"], []]
})

df8.explode("skills")

   name  skills
0  Ravi  Python
1  Amit     NaN

In [4]:
df8.isna()

    name  skills
0  False   False
1  False   False

In [5]:
df8.isna().sum()

name      0
skills    0
dtype: int64

In [7]:
df8.dropna()

   name    skills
0  Ravi  [Python]
1  Amit        []

In [10]:
df8.fillna(0)

   name    skills
0  Ravi  [Python]
1  Amit        []

In [15]:
df8.isnull().sum()

name      0
skills    0
dtype: int64

In [14]:
df8.dropna(how="all")

   name    skills
0  Ravi  [Python]
1  Amit        []

In [17]:
df8['age']=[25, None]

In [18]:
df8["age"].fillna(df8["age"].mean())

0    25.0
1    25.0
Name: age, dtype: float64

In [20]:
df8["salary"]=[50000, None]

In [21]:
df8["salary"] = df8["salary"].fillna(df8["salary"].median())

In [22]:
df8#.dropna()

   name    skills   age   salary
0  Ravi  [Python]  25.0  50000.0
1  Amit        []   NaN  50000.0

In [24]:
import pandas as pd
import numpy as np

df9 = pd.DataFrame({
    "name": ["Ravi","Amit","Sara","John"],
    "age": [25, np.nan, 30, np.nan],
    "salary": [50000, 60000, None, 70000]
})

In [26]:
df9.isna().sum()/len(df9)

name      0.00
age       0.50
salary    0.25
dtype: float64

In [27]:
missing_percent = df.isna().mean() * 100
missing_percent.sort_values(ascending=False)

age       50.0
salary    25.0
name       0.0
dtype: float64